### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by 0rp0N** [clxmente/spotify-obs#2]
I might just be to dumb to follow the instructions from the website but i cant seem to get it to show the current song played.

I joined the Lanyard discord server, i got my Discord ID but when i submit my discord ID the page that comes up is blank. When i go to the customize tab and take that URL with my discord ID in it to add as a browser Source in OBS, it is just blank. 

Not sure if it is something i am doing wrong but i would love to hear back.

If the page after the discord ID submit isnt supposed to show anything could it be that the OBS is the wrong version?

**Comment by clxmente** [comment]
hmm, there's a few common things people seem to run into, if none of these work you can add me on discord and we can try and work through it :)

make sure you:
* are listening to something on spotify (it will be blank/empty if no song is playing)
* are **not appearing offline** on discord
* have your spotify status enabled on discord (when you play something, discord should show what you are listening to)

Something else I've had to see people do is go into the lanyard discord and run the command `/who`. Only had this happen a few times but for some reason lanyard wasn't registering them until they ran this command. 

You can also make sure that lanyard is working by running the `/spotify` command in the lanyard discord server, and the song you are listening to should appear at the bottom of the message. 

If all of this is working, but the obs thing still doesn't show up we can look more into it :)

**Comment by 0rp0N** [comment]
Okay so far i did the /Who commands and it seems to give me a lanyard url but the K/V Keys is empty. Not sure that matters. The interesting thing is that the spotify command isnt giving a song. When i check my discord profile however i see what i am listening too. 
Thank you  for the quick reply.

**Comment by 0rp0N** [comment]
So i posted in the support chat on that discord since it seems to be something with the server or something i missed. And they pointed me to the pinned messages. The first thing was legit what fixed it for me. Had top make sure the server is sharing my activity. Thank you for pointing me in the right direction and have a great rest of your day.

**Comment by clxmente** [comment]
Ahhh, I completely forgot about that. I'll add a troubleshooting section on the website with these tips, thank you!
